languageCode = "en"
languageName = "English"
weight = 1

title = "mattstrayer"
# logo = "img/logo.jpg"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"


[params.author]
name = "Matt Strayer"
image = "img/author.jpg"
# headline = "I'm only human"
# bio = "A little bit about you"
links = [
  { email = "mailto:hello@your_domain.com" },
  { github = "https://github.com/mattstrayer" },
  { twitter = "https://twitter.com/matt_strayer" },
  { linkedin = "https://linkedin.com/in/mattstrayer" },
]
