languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Matt Strayer"
# logo = "img/logo.jpg"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
name = "Matt Strayer"
image = "img/author.jpg"
# headline = "I'm only human"
# bio = "A little bit about you"
links = [
  { email = "mailto:hello@your_domain.com" },
  { github = "https://github.com/mattstrayer" },
  { twitter = "https://twitter.com/matt_strayer" },
]
