baseURL = "https://www.mattstrayer.com/"
languageCode = "en-us"
title = "matt strayer"
theme = "hugo-theme-basic"

[frontmatter]
  date = ["publishDate", "date", "lastmod"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = "dracula"
    tabWidth = 4

# hugo theme basic, options
enableEmoji = true 
copyright = "© 2020, theme by: <a href='https://github.com/siegerts/hugo-theme-basic'>@siegerts</a>"
description = "Matt Strayer blog, links, projects."

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":rocket:"
  twitter = "matt_strayer"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

# [[params.menu]]
#   name = "post series"
#   url = "series/"
  
[[params.menu]]
  name = "about"
  url = "about/"