baseURL = "https://www.mattstrayer.com/"
languageCode = "en-us"
title = "matt strayer"
theme = "hugo-theme-basic"


# hugo theme basic, options
enableEmoji = true 
copyright = "© 2022 Copyright Matt Strayer (<a href='https://twitter.com/matt_strayer' class='link black-40'>@matt_strayer</a>). All rights reserved."
description = "Matt Strayer blog, links, projects."

[frontmatter]
  date = ["publishDate", "date", "lastmod"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    style = "dracula"
    tabWidth = 4



[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":rocket:"
  twitter = "matt_strayer"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

# [[params.menu]]
#   name = "post series"
#   url = "series/"
  
[[params.menu]]
  name = "about"
  url = "about/"
