# netlify.toml

# [[redirects]]
#   from = "https://boring-pasteur-d5a87b.netlify.app/*"
#   to = "https://www.mattstrayer.com/:splat"
#   status = 301
#   force = true #COMMENT: ensure that we always redirect
[build]
command = "hugo mod get -u && hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
NODE_ENV = "production"
GO_VERSION = "1.17"
TZ = "UTC" # Set to preferred timezone

[context.production.environment]
HUGO_VERSION = "0.92.2"
HUGO_ENV = "production"
